#!/bin/bash
# file name make-package
# Make .deb package

if [ $# -ne 2 ]; then
        echo "please specify version and revision, es: 1.0.0 1"
		exit 1
fi

DIR=/tmp
PACKAGE="xscreensaver-caffeine-rs_$1-$2_all"
TARGET=$DIR/$PACKAGE
APPL=$TARGET/usr/share/applications
BINS=$TARGET/usr/local/bin/

cargo build --release

mkdir $TARGET
cp -r DEBIAN $TARGET
mkdir -p $APPL
cp resources/xscreensaver-caffeine-rs.desktop $APPL
mkdir -p $BINS
cp target/release/xscreensaver-caffeine-rs $BINS

#chown -R root:root $DIR

dpkg-deb --build --root-owner-group $TARGET

rm -rf $TARGET

ls -lrt $DIR/*.deb
